### ISSUE TITLE
[Remove Lowercase Limitation] Disable force lowercase for the router

### ISSUE THREAD

**Issue by DBarnes2** [gp-seattle/rms-app#50] opened 2021-07-15 04:05 UTC
Storypoints: 1

Need to make corresponding test changes

Need to make the change in DB constants to change everything to have the first letter uppercase.

Corresponding change in the DBSeeds to expect uppercase variables.

Context: https://github.com/gp-seattle/rms-app/wiki/Remove-Lowercase-Limitation

**Comment by yauj** [comment] 2021-07-21 19:23
Ended up being a duplicate of 2 previous tasks. Closing this issue.

**Closed by yauj** 2021-07-21 19:23 UTC
Labels: task
